name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report!  Please fill out the sections below to help us diagnose the problem.
  - type: markdown
    attributes:
      value: |
        **Questions / usage help belong in Discord:** https://discord.dontdiegloriously.com  
        Use this form only for bugs/features.
  - type: input
    id: environment
    attributes:
      label: Environment
      description: What operating system, browser or runtime are you using?  Include version numbers if possible.
      placeholder: e.g. macOS 12.5, Python 3.10, Chrome 105
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the behaviour.  Include any relevant logs or screenshots.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
      description: What actually happened?  Include error messages or stack traces if applicable.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false